name: Build with Buildozer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: $HOME/.buildozer/android/platform/android-sdk
      ANDROID_HOME: $HOME/.buildozer/android/platform/android-sdk
      ANDROID_NDK_HOME: $HOME/.buildozer/android/platform/android-ndk

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install buildozer
        run: |
          pip install wheel
          pip install cython
          pip install buildozer

      - name: Install Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install Android SDK
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O android-sdk-tools.zip
          unzip -qq android-sdk-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools/latest
          rm android-sdk-tools.zip
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0"

      - name: Install Android NDK
        run: |
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "ndk;21.4.7075529"

      - name: Build with Buildozer
        run: buildozer android debug
